In [34]:
%matplotlib inline

import sqlite3
import pandas as pd
import numpy as np
import nltk
import string
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import confusion_matrix
from sklearn import metrics
from sklearn.metrics import roc_curve, auc
from nltk.stem.porter import PorterStemmer

from sklearn import datasets, neighbors
from sklearn.cross_validation import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.cross_validation import cross_val_score
from collections import Counter
from sklearn.metrics import accuracy_score
from sklearn import cross_validation

In [35]:
data = pd.read_pickle('amazon_food_review_after_preprocess')

In [36]:
data.head()

Id   ProductId          UserId                  ProfileName  \
138706  150524  0006641040   ACITT7DI6IDDL              shari zychinski   
138688  150506  0006641040  A2IW4PEEKO2R0U                        Tracy   
138689  150507  0006641040  A1S4A3IQ2MU7V4        sally sue "sally sue"   
138690  150508  0006641040     AZGXZ2UUK6X  Catherine Hallberg "(Kate)"   
138691  150509  0006641040  A3CMRKGE0P909G                       Teresa   

        HelpfulnessNumerator  HelpfulnessDenominator     Score        Time  \
138706                     0                       0  positive   939340800   
138688                     1                       1  positive  1194739200   
138689                     1                       1  positive  1191456000   
138690                     1                       1  positive  1076025600   
138691                     3                       4  positive  1018396800   

                                           Summary  \
138706                   EVERY book is educational   
138688  Love the book, miss the hard cover version   
138689               chicken soup with rice months   
138690      a good swingy rhythm for reading aloud   
138691             A great way to learn the months   

                                                     Text  \
138706  this witty little book makes my son laugh at l...   
138688  I grew up reading these Sendak books, and watc...   
138689  This is a fun way for children to learn their ...   
138690  This is a great little book to read aloud- it ...   
138691  This is a book of poetry about the months of t...   

                                              CleanedText  
138706  b'witti littl book make son laugh loud recit c...  
138688  b'grew read sendak book watch realli rosi movi...  
138689  b'fun way children learn month year learn poem...  
138690  b'great littl book read nice rhythm well good ...  
138691  b'book poetri month year goe month cute littl ...

In [37]:
data.sort_values('Time',inplace = True)

In [38]:
data.head()

Id   ProductId          UserId               ProfileName  \
138706  150524  0006641040   ACITT7DI6IDDL           shari zychinski   
138683  150501  0006641040   AJ46FKXOVC7NR        Nicholas A Mesiano   
417839  451856  B00004CXX9   AIUWLEQ1ADEG5          Elizabeth Medina   
346055  374359  B00004CI84  A344SMIA5JECGM           Vincent P. Ross   
417838  451855  B00004CXX9   AJH6LUC1UT1ON  The Phantom of the Opera   

        HelpfulnessNumerator  HelpfulnessDenominator     Score       Time  \
138706                     0                       0  positive  939340800   
138683                     2                       2  positive  940809600   
417839                     0                       0  positive  944092800   
346055                     1                       2  positive  944438400   
417838                     0                       0  positive  946857600   

                                                  Summary  \
138706                          EVERY book is educational   
138683  This whole series is great way to spend time w...   
417839                               Entertainingl Funny!   
346055                            A modern day fairy tale   
417838                                         FANTASTIC!   

                                                     Text  \
138706  this witty little book makes my son laugh at l...   
138683  I can remember seeing the show when it aired o...   
417839  Beetlejuice is a well written movie ..... ever...   
346055  A twist of rumplestiskin captured on film, sta...   
417838  Beetlejuice is an excellent and funny movie. K...   

                                              CleanedText  
138706  b'witti littl book make son laugh loud recit c...  
138683  b'rememb see show air televis year ago child s...  
417839  b'beetlejuic well written movi everyth excel a...  
346055  b'twist rumplestiskin captur film star michael...  
417838  b'beetlejuic excel funni movi keaton hilari wa...

In [40]:
count_vect = CountVectorizer() #scikit-learn countevectorizer
final_counts = count_vect.fit_transform(data['CleanedText'].values)

In [41]:
final_counts

<364171x71624 sparse matrix of type '<class 'numpy.int64'>'
	with 11460537 stored elements in Compressed Sparse Row format>

In [26]:
x_tr = final_counts[0:254920]
x_tst = final_counts[254920:]

In [27]:
y_tr = data['Score'][:254920]
y_tst = data['Score'][254920:]

In [29]:
knn = KNeighborsClassifier(n_neighbors=1)

In [30]:
knn.fit(x_tr, y_tr)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')

In [ ]:
pred = knn.predict(x_tst)

In [ ]:
acc = accuracy_score(y_tjst, pred, normalize=True) * float(100)
print('\n****Test accuracy for k = 1 is %d%%' % (acc))

In [42]:
from sklearn.model_selection import TimeSeriesSplit
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8],[9,10],[11,12]])
y = np.array([1, 2, 3, 4,5,6])
tscv = TimeSeriesSplit(n_splits=3)
print(tscv)  


TimeSeriesSplit(max_train_size=None, n_splits=3)


In [11]:
TimeSeriesSplit(max_train_size=None, n_splits=3)
for train_index, test_index in tscv.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    print(X_train,":",X_test)
    y_train, y_test = y[train_index], y[test_index]
    print(y_train,":",y_test)


TRAIN: [0 1 2] TEST: [3]
[[1 2]
 [3 4]
 [5 6]] : [[7 8]]
[1 2 3] : [4]
TRAIN: [0 1 2 3] TEST: [4]
[[1 2]
 [3 4]
 [5 6]
 [7 8]] : [[ 9 10]]
[1 2 3 4] : [5]
TRAIN: [0 1 2 3 4] TEST: [5]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]] : [[11 12]]
[1 2 3 4 5] : [6]


In [43]:
polarity = data['Score']

In [48]:
polarity.value_counts()

positive    307061
negative     57110
Name: Score, dtype: int64

In [55]:
polarity.iloc[3]

'positive'

In [44]:
tscv_data = TimeSeriesSplit(n_splits=10)
tscv_data

TimeSeriesSplit(max_train_size=None, n_splits=10)

In [45]:
cv_scores= []

In [ ]:
for train_index, test_index in tscv_data.split(final_counts):
    print("TRAIN:", train_index, "TEST:", test_index)
    cv_score_temp = []
    X_train, X_test = final_counts[train_index], final_counts[test_index]
    #print(X_train,":",X_test)
    y_train, y_test = polarity.iloc[train_index], polarity.iloc[test_index]
    #print(y_test.value_counts())
    #print(y_train,":",y_test)
    knn.fit(X_train, y_train)
    pred = knn.predict(X_test)
    acc = accuracy_score(y_test, pred, normalize=True) * float(100)
    print("ACCURACY:",acc)
    cv_score_temp.append(acc)

TRAIN: [    0     1     2 ... 33108 33109 33110] TEST: [33111 33112 33113 ... 66214 66215 66216]
